CREATE TABLE threads (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id > 0),
	category_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL,
	CONSTRAINT fk_threads_category FOREIGN KEY(category_id) REFERENCES categories(id)
);
