CREATE TABLE threads (
	id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY CHECK (id > 0),
	category_id INT NOT NULL,
	title VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL
);
CREATE INDEX threads_category_id ON threads (category_id);
